In [1]:
import numpy as np 

In [3]:
arr = np.arange(1 , 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[6]

np.int64(7)

In [5]:
arr[ 2:7]

array([3, 4, 5, 6, 7])

In [ ]:
arr = np.arange(1, 31).reshape(6, 5)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])