In [ ]:
# paracrice question  numpy array 1 to 10
# aply sum min and max


In [2]:
import numpy as np

In [34]:
arr =np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
sum =np.sum(arr)
sum

np.int64(55)

In [41]:
min =np.min(arr)
min

np.int64(1)

In [ ]:
max =np.max(arr)
max


np.int64(10)

In [ ]:
 # create an array from 1 to 12 and reshape it into a 3×4 matrix.



In [43]:
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [45]:
arr.reshape(3,4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#valid Sudokobb


In [3]:
import numpy as np 

In [4]:
s =np.array([
    [1,2,3,4,5,6,7,8,9],
    [6,5,8,9,7,2,3,1,4],
    [5,8,9,6,4,7,2,1,4],

    [3,2,5,6,7,8,9,4,1],
    [4,6,3,8,2,1,5,7,9],
    [9,8,7,6,5,4,3,2,1],

    [7,8,9,4,3,5,6,2,1],
    [2,4,5,3,6,7,9,8,1],
    [6,7,9,8,2,1,3,4,5],
])

In [5]:
b = np.sum(s , axis = 1)
for i in b :
    if i != 45 :
        print("sudoku is  invalid ")
        break
    else: 
        print ( "for all rows sudoku is valid ")

for all rows sudoku is valid 
for all rows sudoku is valid 
sudoku is  invalid 


In [ ]:
b = np.sum(s, axis = 0)
for i in b :
    if i != 45:
        print( " sudoku is invalid")
        break
else:
    print("for columns it is valid ")    


 sudoku is invalid
